### ISSUE TITLE
split_bed.py errors

### ISSUE THREAD

**Issue by AllenAkhaumere** [bioinform/neusomatic#11]
I'm having issues working with the split_bed source code. 
raise NotImplementedError(help_str)
NotImplementedError: "sortBed" does not appear to be installed or on the path, so this method is disabled.  Please install a more recent version of BEDTools and re-import to use this method.
I installed the recent version of BEDTools but the problem persist. Any idea what the issues might be?

**Comment by msahraeian** [comment]
@AllenAkhaumere happy to see your interest in NeuSomatic. This error usually happens when bedtools bin folder is not in your PATH. You can check that by `which sortBed`.  
If it is missing from PATH you can export it as:
` export PATH="/PATH/TO/bedtools2/bin:$PATH"`. 

I would recommend to use anaconda (or miniconda) as explained [here](https://github.com/bioinform/neusomatic#availability) to install all the python packages. Then you should make sure the conda binary folder is in your PATH by ` export PATH="/PATH/TO/anconda/bin:$PATH"`.

**Comment by AllenAkhaumere** [comment]
OK
