### ISSUE TITLE
support for singularity?  

### ISSUE THREAD

**Issue by GodloveD** [bioinform/neusomatic#56]
Hi there!

From what I can gather, the `prepare_callers-scripts.sh` command and associated scripts [here](https://github.com/bioinform/neusomatic/tree/master/ensemble_docker_pipelines) will only work with Docker.  Do I have that right?  Are there any plans to develop a similar pipeline using [Singularity](https://github.com/sylabs/singularity)?  

Looks like the somaticseq project has already created a [similar variant](https://github.com/bioinform/somaticseq/tree/master/utilities/singularities) so perhaps development would not be too complicated.  

Thanks for considering this request!

**Comment by msahraeian** [comment]
@GodloveD 
I added Singularity support in #58 . 
Please pull master, and check the [README](https://github.com/bioinform/neusomatic/tree/master/ensemble_docker_pipelines). You can enable Singularity instead of Docker if you use `--singularity`argument.

BTW, please note that we have used the following 5 callers in the latest [pre-trained ensemble models](https://github.com/bioinform/neusomatic#trained-network-models) which are trained on SEQC-II  data: (MuTect2, Strelka2, MuSE, SomaticSniper, VarDict)

**Comment by GodloveD** [comment]
Thanks @msahraeian !
